from t08_flask_mysql.app.my_project.auth.domain.orders.airline_companies import AirlineCompanies
from t08_flask_mysql.app.my_project.auth.domain.orders.airport import Airport
from t08_flask_mysql.app.my_project.auth.domain.orders.city import City
from t08_flask_mysql.app.my_project.auth.domain.orders.country import Country
from t08_flask_mysql.app.my_project.auth.domain.orders.flight import Flight
from t08_flask_mysql.app.my_project.auth.domain.orders.flights_has_passengers import FlightHasPassengers
from t08_flask_mysql.app.my_project.auth.domain.orders.plane import Plane
from t08_flask_mysql.app.my_project.auth.domain.orders.region import Region
from t08_flask_mysql.app.my_project.auth.domain.orders.route_points import RoutePoints
